version: '3.8'

services:
    library-front:
        image: nespouique/library-front:latest
        container_name: library-front
        ports:
            - '80:80'
        restart: unless-stopped
        environment:
            - NGINX_API_URL=https://library-ws.example.com # URL complète
            - NGINX_API_HOST=library-ws.example.com # Host sans port
